# Generated by Django 5.0.3 on 2025-05-09 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('contract', 'name'), name='unique_project_name_per_contract'),
        ),
    ]
